### ISSUE TITLE
管理页面显示不正常

### ISSUE THREAD

**Issue by xiaodaocool** [hacklcx/HFish#10]
![image](https://user-images.githubusercontent.com/18043903/63068742-f45f1a00-bf46-11e9-9ca8-381b7ef54aba.png)

**Comment by sanjinhub** [comment]
强制刷新试试？

**Comment by xiaodaocool** [comment]
> 强制刷新试试？

刷新不起作用
chrome和firefox显示都不正常，edge显示正常，其余未测试

**Comment by sanjinhub** [comment]
@xiaodaocool 可以加个微信 微信方便查看问题

**Comment by xiaodaocool** [comment]
adblock插件的原因
