### ISSUE TITLE
缓存存在问题，把setting.go  函数initCahe()注释掉才能启动

### ISSUE THREAD

**Issue by lingfeng2008** [hacklcx/HFish#108]
root@ll-virtual-machine:~/HFish-0.6.3# ./HFish version
v0.6.3
root@ll-virtual-machine:~/HFish-0.6.3# ./HFish run
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] Loaded HTML Templates (2): 
	- 
	- index.html

[GIN-debug] GET    /static/*filepath         --> HFish/vendor/github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (2 handlers)
[GIN-debug] HEAD   /static/*filepath         --> HFish/vendor/github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (2 handlers)
[GIN-debug] GET    /                         --> HFish/utils/setting.RunWeb.func1 (2 handlers)
[GIN-debug] POST   /api/v1/post/report       --> HFish/view/api.ReportWeb (3 handlers)
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] Loaded HTML Templates (2): 
	- 
	- index.html

[GIN-debug] GET    /static/*filepath         --> HFish/vendor/github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (2 handlers)
[GIN-debug] HEAD   /static/*filepath         --> HFish/vendor/github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (2 handlers)
[GIN-debug] GET    /                         --> HFish/utils/setting.RunDeep.func1 (2 handlers)
[GIN-debug] POST   /api/v1/post/deep_report  --> HFish/view/api.ReportDeepWeb (3 handlers)
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /api/v1/post/plug_report  --> HFish/view/api.ReportPlugWeb (3 handlers)
panic: interface conversion: interface {} is nil, not int64

goroutine 1 [running]:
HFish/utils/setting.initCahe()
	/ext-go/1/src/HFish/utils/setting/setting.go:159 +0xce5
HFish/utils/setting.Run()
	/ext-go/1/src/HFish/utils/setting/setting.go:392 +0xef9
main.main()
	/ext-go/1/src/HFish/main.go:22 +0x1bc

**Comment by T4di5** [comment]
项目不维护了，散了不、吧
