### ISSUE TITLE
假设有个 ip 频繁访问服务器，可以用这个项目做什么吗？

### ISSUE THREAD

**Issue by mofadeyunduo** [hacklcx/HFish#11]
假设有个 ip 频繁访问服务器，可以用这个项目做什么吗？有什么具体的样例呢？

**Comment by sanjinhub** [comment]
主要记录黑客攻击手段，具体可以百度 ”蜜罐“

比如说频繁访问可以确定这个IP可以进入黑名单了，可以配合防火墙使用。很多种玩法，具体看思路。
