### ISSUE TITLE
自定义蜜罐没生效

### ISSUE THREAD

**Issue by notjac** [hacklcx/HFish#114]
[pot_name]status = 1    addr=0.0.0.0:3389    info={{addr}}
在配置文件config.ini上添加信息（保存过重启的HFish.exe）
结果其他电脑远程上去了，但是后台页面上没有记录。。。。

**Comment by notjac** [comment]
Sorry , i dont know what you cant understand Chinese. 
I have one trouble about the section HFish defined by user own, and i did it by step, finally this **custom** didnt be showed in the one module  of  mian page.
After i changed parameters in the file _config.ini_ （[pot_name]status = 1 addr=0.0.0.0:3389 info={{addr}}），i also reload the HFish。But，it still was worry.

**Comment by yw6minggege** [comment]
蜜罐开启的都是假端口，没办法真实连接，只能记录扫描时的记录吧，仅供参考
