### ISSUE TITLE
Problem with "/data page" and "/fish page"

### ISSUE THREAD

**Issue by MoJl4yH** [hacklcx/HFish#115]
Hello guys, sorry for my english, because it`s not my main language. I have problem, i use your honeypot for study in my university, and yesterday on my trap was be attack on port "http proxy". Amount connection was about 1 million (see picture [1]), and attack continued, because of this, I could not connect to API. I had to off port "http proxy" in configuration file, and i could open API. i saw two problem. First, on data page, country, from which the attack was carried out had big red circly, VERY BIG. And this big circly cover the others country (see picture [2]). Second problem with list on page /fish because of my server had very heavy load. on port "http proxy". on list at page /fish were different entries that shouldn't be (see picture [3]). I deleted all that been excess, but how avoid this in the future?
How i can fixed two these problems?
Also, how i can insert ip in black list? Because one ip address ddos my "proxy http" port.

![Pic1](https://user-images.githubusercontent.com/26865710/96427448-3c429680-1207-11eb-8ae6-c84bbbce5f4c.png)
![Pic2](https://user-images.githubusercontent.com/26865710/96427450-3d73c380-1207-11eb-901d-ab09f099c3ca.PNG)
![Pic3](https://user-images.githubusercontent.com/26865710/96427454-3e0c5a00-1207-11eb-8146-c1c6866c5cdd.jpg)

And also, how i can download all log file, that it will have format as table? I tried use python library Json, but it dowload log file in formar {type1:type2}. i want do analysis attacker, and for this i need have format how data base table. 
Thanks guys!

**Comment by notjac** [comment]
i want to ask one question, did you use the custom in the your one pictrue？

**Comment by MoJl4yH** [comment]
> i want to ask one question, can you use the custom in the your 1th pictrue？

You mean, can i use custom honeypot? Then yes.
I was creating custom honeypot for fun. but now me sufficiently those trap who have already created.

**Comment by notjac** [comment]
i cant create custom honeypot......and i dont know why.
could you tell me how did it? thankyou!

**Comment by MoJl4yH** [comment]
> i cant create custom honeypot......and i dont know why.
> could you tell me how did it? thankyou!
Well, i just followed instruction at docs page "https://hfish.io/docs/#/pot/custom"
Describe your problem, maybe I can help.

**Comment by notjac** [comment]
After i changed parameters in the file config.ini （[pot_name]status = 1 addr=0.0.0.0:3389 info={{addr}}），i also reload the HFish。But，it still was worry.

**Comment by MoJl4yH** [comment]
> After i changed parameters in the file config.ini （[pot_name]status = 1 addr=0.0.0.0:3389 info={{addr}}），i also reload the HFish。But，it still was worry.

You sure, that with your custom honeypot is someone trying to connect? Maybe custom trap working, but nobody dont want connection for your trap?
Just i try create custom trap, and it work it. Try to run custom honeypot and will use nmap, that check.
![pic1](https://user-images.githubusercontent.com/26865710/96465781-05ce4100-1232-11eb-8e9c-280007e06639.png)
![Pic2](https://user-images.githubusercontent.com/26865710/96465787-06ff6e00-1232-11eb-8c1b-4f439bcdd615.PNG)
![pic3](https://user-images.githubusercontent.com/26865710/96465789-06ff6e00-1232-11eb-8daf-9d4f96a6b777.PNG)

**Comment by notjac** [comment]
ye,i tried to connect it by port 3389, and its ok......
whatever it just didt display the number. i also checked version  0.6.3 the most newest.
i really have no way.

**Comment by MoJl4yH** [comment]
> maybe win10 didnt support custom honeypot......

I'm not sure if the problem is with the system selection, but you can install hfish on linux system, for example ubuntu or debian

**Comment by notjac** [comment]
> > maybe win10 didnt support custom honeypot......
> 
> I'm not sure if the problem is with the system selection, but you can install hfish on linux system, for example ubuntu or debian

thankyou for your patience
