### ISSUE TITLE
接口为空

### ISSUE THREAD

**Issue by passerbyon** [hacklcx/HFish#117]
panic: interface conversion: interface {} is nil, not int64
在linux中执行的，这个是什么原因

**Comment by nszy007** [comment]
同样的问题。

**Comment by shiyishiaa** [comment]
> panic: interface conversion: interface {} is nil, not int64
> 在linux中执行的，这个是什么原因



> 同样的问题。

下载相同版本的release包，替换掉db目录下的`hfish.db`文件即可。

**Comment by my417** [comment]
该问题是由于数据库没有更新，读取失败，可以查看发布包说明进行更新，或者安装新版本即可。
