### ISSUE TITLE
Emergency stop

### ISSUE THREAD

**Issue by Ella-Miller** [hacklcx/HFish#118]
[root@******** HFish-0.6.3-linux-amd64]# ./HFish run
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] Loaded HTML Templates (2):
        -
        - index.html

[GIN-debug] GET    /static/*filepath         --> HFish/vendor/github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (2 handlers)
[GIN-debug] HEAD   /static/*filepath         --> HFish/vendor/github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (2 handlers)
[GIN-debug] GET    /                         --> HFish/utils/setting.RunWeb.func1 (2 handlers)
[GIN-debug] POST   /api/v1/post/report       --> HFish/view/api.ReportWeb (3 handlers)
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] Loaded HTML Templates (2):
        -
        - index.html

[GIN-debug] GET    /static/*filepath         --> HFish/vendor/github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (2 handlers)
[GIN-debug] HEAD   /static/*filepath         --> HFish/vendor/github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (2 handlers)
[GIN-debug] GET    /                         --> HFish/utils/setting.RunDeep.func1 (2 handlers)
[GIN-debug] POST   /api/v1/post/deep_report  --> HFish/view/api.ReportDeepWeb (3 handlers)
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /api/v1/post/plug_report  --> HFish/view/api.ReportPlugWeb (3 handlers)
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb050ec]

goroutine 22 [running]:
HFish/core/protocol/redis.Start(0xc000028f01, 0xc)
        /ext-go/1/src/HFish/core/protocol/redis/redis.go:26 +0xbc
created by HFish/utils/setting.Run
        /ext-go/1/src/HFish/utils/setting/setting.go:277 +0x4ed

**Comment by shiyishiaa** [comment]
我的机器也是报invalid memory address or nil pointer dereference这个错误，不过版本是0.6.4
