### ISSUE TITLE
Bug反馈与建议

### ISSUE THREAD

**Issue by XRSec** [hacklcx/HFish#124]
## 建议
1. 建议修改title为502 Bad Gateway
2. 建议修改login icon  echo . > icon.png
3. 一键清空或者自定义页面显示数量
4.  WEB 页面 无法查看具体信息
5. 建议图片路劲随机生成，怕反蜜罐

## bug
1. 一键清空失效
2. IP抓错了
![image](https://user-images.githubusercontent.com/73819467/102515337-986f4d00-40c8-11eb-8547-ee0e369df4d9.png)
3. 建议邮件设置策略 瞬间700+攻击邮箱服务器直接限制 情报也限制
4. WebHook告警通知 飞书无法使用，淦，没事
5. 我就想骗一个 0day，1day，我太难了
6. 蜜罐维护者你们太难了

**Comment by zygds** [comment]
点击查看详情我找到了在这
![image](https://user-images.githubusercontent.com/73819467/102516543-ecc6fc80-40c9-11eb-85a0-9e8cdaeff350.png)

**Comment by zygds** [comment]
但是好像配置了日志服务器无反应
