### ISSUE TITLE
安装以后admin登录不了

### ISSUE THREAD

**Issue by 1200062029** [hacklcx/HFish#135]
按照文档 admin admin登录 无效

**Comment by zhiduopc** [comment]
我WIN10也是HFish-0.6.5-windows-amd64版提示登录失败，用户名或密码不正确，不知道咋回事更新了的原因？WIN10下 这样./HFish.exe run也执行不了要把./去掉不然要报错
D:\HFish-0.6.5-windows-amd64>./HFish.exe run
'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by zhiduopc** [comment]
原来密码改了，网站没有同步更新。。。=HFish@2020= 这是新密码，WIN10下 这样./HFish.exe run也执行不了要把./去掉不然要报错
D:\HFish-0.6.5-windows-amd64>./HFish.exe run
'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by snuglove** [comment]
现在密码是多少了 我刚下载了2.0版  admin =HFish@2020=  都不对

**Comment by snuglove** [comment]
刚才找了一下数据库是Bcrypt加密.直接改了,省的找来找去了

**Comment by PeterJoins** [comment]
作者啊，能给个账号密码嘛，真是太难了。。。还不能直接改数据库

**Comment by snuglove** [comment]
@PeterJoins  上面提供了加密方式,你使用相同的方式加密修改即可,不能修改的原因?

**Comment by PeterJoins** [comment]
> 
> 
> @PeterJoins 上面提供了加密方式,你使用相同的方式加密修改即可,不能修改的原因?

我部署的不能新建模板，文档里说是有内置模板，里面也没有
