### ISSUE TITLE
分布式集群下 所有节点都是红点 ？

### ISSUE THREAD

**Issue by 1200062029** [hacklcx/HFish#138]
我看文档上也都是红点，我装起来以后全是红点，但是扫描却是生效的
红点到底是正常还是不正常？会变绿吗?

**Comment by starnightcyber** [comment]
好像没啥太大的影响，可以检测到扫描等攻击行为。

**Comment by Dawnnnnnn** [comment]
大概率是adblock插件的问题，把class标记成广告了，我换了新的class名字就好了
