### ISSUE TITLE
添加节点时会提示"生成节点安装包失败数据库错误"

### ISSUE THREAD

**Issue by pykiller** [hacklcx/HFish#142]

**Comment by pykiller** [comment]
能上传docker么

**Comment by vinsonliux** [comment]
我也遇到了这个问题，目前已解决，当你的模板里包含的服务和现有服务有冲突的时候，就无法生成，把ssh或者其他冲突端口改掉就好了

**Comment by pykiller** [comment]
> 我也遇到了这个问题，目前已解决，当你的模板里包含的服务和现有服务有冲突的时候，就无法生成，把ssh或者其他冲突端口改掉就好了

谢谢老哥

**Comment by HDsky** [comment]
```
Error 1292: Incorrect datetime value: '0000-00-00' for column 'report_time' at row 1
```

我这边也是同样的提示，看log报这个错误，看上去是mysql版本的问题

**Comment by StephenJose-Dai** [comment]
> > 我也遇到了这个问题，目前已解决，当你的模板里包含的服务和现有服务有冲突的时候，就无法生成，把ssh或者其他冲突端口改掉就好了
> 
> 谢谢老哥

我就一个ssh 22是冲突的，其他服务端口不冲突，但是还是不行，是啥问题

**Comment by StephenJose-Dai** [comment]
> ```
> Error 1292: Incorrect datetime value: '0000-00-00' for column 'report_time' at row 1
> ```
> 
> 我这边也是同样的提示，看log报这个错误，看上去是mysql版本的问题

官文似乎没有提到环境要求，我用的是mysql57的，也报这个，不知道老哥你解决了没有？可以分享下么？

**Comment by HDsky** [comment]
> > ```
> > Error 1292: Incorrect datetime value: '0000-00-00' for column 'report_time' at row 1
> > ```
> > 
> > 
> > 我这边也是同样的提示，看log报这个错误，看上去是mysql版本的问题
> 
> 官文似乎没有提到环境要求，我用的是mysql57的，也报这个，不知道老哥你解决了没有？可以分享下么？

https://stackoverflow.com/questions/35565128/mysql-incorrect-datetime-value-0000-00-00-000000

**Comment by liiir** [comment]
原帖链接：https://blog.csdn.net/java_cxrs/article/details/105775460

**Comment by HDsky** [comment]
> 原帖链接：https://blog.csdn.net/java_cxrs/article/details/105775460
> 
> vim /etc/my.cnf
> 
> #添加以下内容
> sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
> 
> systemctl restart mysqld
> 
> 实践过成功了

不适用于ubuntu 20.04 LTS，且这样只是手动设置sql_mode，最主要的是移除掉sql_mode中的```NO_ZERO_IN_DATE,NO_ZERO_DATE``` 两项，希望各位复制粘贴的时候能够想清楚别人为什么这么做

**Comment by HDsky** [comment]
在Ubuntu 安装的mysql8中，可以通过填加启动参数的方式更改 sql_mode

编辑 `/lib/systemd/system/mysql.service`

```
ExecStart=/usr/sbin/mysqld --sql-mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
```
> 此处仅除去默认参数中的`NO_ZERO_DATE`,具体填写的sql_mode请根据实际需要自行判别

然后重新加载配置文件，重启mysql
```
sudo systemctl daemon-reload
sudo systemctl restart mysql
```
这种方式在mysql重启后不会失效

**Comment by PeterJoins** [comment]
新增节点的时候报错，提示“生成节点安装包失败数据库错误”，日志如下，怎么解决呢
[2021-04-16 14:21:15]  Error 1292: Incorrect datetime value: '0000-00-00' for column 'report_time' at row 1

**Comment by PeterJoins** [comment]
> 
> 
> 在Ubuntu 安装的mysql8中，可以通过填加启动参数的方式更改 sql_mode
> 
> 编辑 `/lib/systemd/system/mysql.service`
> 
> ```
> ExecStart=/usr/sbin/mysqld --sql-mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
> ```
> 
> > 此处仅除去默认参数中的`NO_ZERO_DATE`,具体填写的sql_mode请根据实际需要自行判别
> 
> 然后重新加载配置文件，重启mysql
> 
> ```
> sudo systemctl daemon-reload
> sudo systemctl restart mysql
> ```
> 
> 这种方式在mysql重启后不会失效

你这个问题怎么解决的呢

**Comment by PeterJoins** [comment]
> 
> 
> 新增节点的时候报错，提示“生成节点安装包失败数据库错误”，日志如下，怎么解决呢
> [2021-04-16 14:21:15] Error 1292: Incorrect datetime value: '0000-00-00' for column 'report_time' at row 1
按如下方式，问题已解决：
set @@global.sql_mode = 'STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
set @@sql_mode = 'STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
