### ISSUE TITLE
有跑起来的伙计吗？用户名密码是啥？

### ISSUE THREAD

**Issue by anyeshe** [hacklcx/HFish#145]
hfish-2.1.0-linux-amd64.tar.gz   这个版本，README里 默认用户名密码为： **admin / OneFish2021**   试了一下不行，github上的用户名密码也不行，完后重置密码也不行
```
./tools resetpwd 123123
reset admin password success.
```

**Comment by NS-Sp4ce** [comment]
tools resetpwd执行后会重置为初始密码，初始密码HFish2021
admin/HFish2021
