### ISSUE TITLE
客户端一直是离线状态

### ISSUE THREAD

**Issue by wangsanshi123** [hacklcx/HFish#148]
客户端日志
Client]2021/06/04 19:34:26 report.go:132: post client data result: {"response_code":1004,"verbose_msg":"请求数据非法"}
[Client]2021/06/04 19:34:26 upgrade.go:43: fetch latest version: 2.3.0
[Client]2021/06/04 19:34:55 upgrade.go:43: fetch latest version: 2.3.0
[Client]2021/06/04 19:35:25 config.go:94: download config success, write: 484
[Client]2021/06/04 19:35:25 config.go:137: new file name: service_LUtKaJEbMSSMbhCgKwnaqBacRCkWxOIq.json
[Client]2021/06/04 19:35:25 config.go:139: same to old file and begin to remove.
[Client]2021/06/04 19:35:25 upgrade.go:43: fetch latest version: 2.3.0
[Client]2021/06/04 19:35:55 utils.go:23: linux exec err: exit status 1
[Client]2021/06/04 19:35:56 utils.go:23: linux exec err: exit status 1
[Client]2021/06/04 19:35:56 report.go:125: client data: {"client_id":"zHXZoy8LGsfYxdjZb8s4elhw","client_ip":"172.16.0.4,172.24.0.1,172.18.0.1,192.168.64.1,172.17.0.1,172.19.0.1,192.168.96.1,172.20.0.1,192.168.80.1,172.22.0.1,172.21.0.1,172.23.0.1,172.25.0.1,172.26.0.1,172.27.0.1,172.28.0.1","client_name":"test1","host_id":"a0a97b3e-c130-4373-8924-e20be497d6ca","platform":"centos","os_arch":"x86_64","time_zone":"CST","cpu_num":1,"mem_total":8370049024,"mem_used":3888173056,"disk_total":158398345216,"disk_used":114453786624,"net_info":"eth0\u0026\u0026fa:16:3e:e7:6b:da\u0026\u0026172.16.0.4\u0026\u0026255.255.240.0|br-4e638f81882c\u0026\u002602:42:51:8f:31:66\u0026\u0026172.24.0.1\u0026\u0026255.255.0.0|br-622758f6eaa8\u0026\u002602:42:61:9b:ca:47\u0026\u0026172.18.0.1\u0026\u0026255.255.0.0|br-8fc4f4edb0ab\u0026\u002602:42:3b:f9:d5:5d\u0026\u0026192.168.64.1\u0026\u0026255.255.240.0|docker0\u0026\u002602:42:3f:0f:ab:6f\u0026\u0026172.17.0.1\u0026\u0026255.255.0.0|br-80eacbcc4b45\u0026\u002602:42:df:10:8a:98\u0026\u0026172.19.0.1\u0026\u0026255.255.0.0|br-b17239f4eca5\u0026\u002602:42:e5:bd:77:82\u0026\u0026192.168.96.1\u0026\u0026255.255.240.0|br-ba9e81c99d95\u0026\u002602:42:68:8f:c9:6a\u0026\u0026172.20.0.1\u0026\u0026255.255.0.0|br-d01497061433\u0026\u002602:42:76:64:cb:68\u0026\u0026192.168.80.1\u0026\u0026255.255.240.0|br-5d98eceac764\u0026\u002602:42:bd:6e:6b:ea\u0026\u0026172.22.0.1\u0026\u0026255.255.0.0|br-31bef3e467d6\u0026\u002602:42:bd:21:66:48\u0026\u0026172.21.0.1\u0026\u0026255.255.0.0|br-c1680eaaedda\u0026\u002602:42:db:0d:dd:a8\u0026\u0026172.23.0.1\u0026\u0026255.255.0.0|br-4a57a092df71\u0026\u002602:42:9a:65:62:2f\u0026\u0026172.25.0.1\u0026\u0026255.255.0.0|veth7898c21\u0026\u0026b6:e1:fc:f7:9b:63|veth7b6d3a0\u0026\u002686:60:7e:39:32:fe|br-23ab1ebd563b\u0026\u002602:42:94:c9:5c:21\u0026\u0026172.26.0.1\u0026\u0026255.255.0.0|br-612684ae4d4c\u0026\u002602:42:b8:7f:36:dd\u0026\u0026172.27.0.1\u0026\u0026255.255.0.0|veth5fb695c\u0026\u0026ca:ac:aa:68:e1:89|vethf993c00\u0026\u0026f2:a5:a1:8b:61:51|veth926fbf4\u0026\u0026e2:09:f4:11:85:38|vetha5f4f14\u0026\u0026a6:82:9a:4d:93:1a|br-4acaaa603123\u0026\u002602:42:f1:49:8f:2a\u0026\u0026172.28.0.1\u0026\u0026255.255.0.0|vethb3ac9ec\u0026\u0026be:84:94:da:05:a1","dns_info":"172.16.0.2|172.16.0.3","bytes_send":193422602,"bytes_recv":107840306,"package_send":511046,"package_recv":514226,"status":"ssh:3:|telnet:2:online|bait:0:disable|ftp:2:online|mysql:3:|redis:2:online"}
[Client]2021/06/04 19:35:56 report.go:132: post client data result: {"response_code":1004,"verbose_msg":"请求数据非法"}
[Client]2021/06/04 19:35:56 upgrade.go:43: fetch latest version: 2.3.0
[Client]2021/06/04 19:36:25 config.go:94: download config success, write: 484
[Client]2021/06/04 19:36:25 config.go:137: new file name: service_AzHdNRHmEMuDPEVcsAAXpwBhvBUTxHIc.json
[Client]2021/06/04 19:36:25 config.go:139: same to old file and begin to remove.
[Client]2021/06/04 19:36:25 upgrade.go:43: fetch latest version: 2.3.0

**Comment by my417** [comment]
2.4版本我们重构了数据库，您必须重新部署。当前我们已经发布了2.5版本，您可以再测试一下。
