### ISSUE TITLE
现在HFish还是开源的吗？代码就是github上提供的所有吗？

### ISSUE THREAD

**Issue by muyuanjin999** [hacklcx/HFish#154]
恳请大佬回答一下 orz

**Comment by cc-sir** [comment]
![image](https://user-images.githubusercontent.com/43071042/126275216-2a422a64-02e0-4979-b1ba-a3efb6b3b918.png)
https://hfish.io/#/

**Comment by muyuanjin999** [comment]
> ![image](https://user-images.githubusercontent.com/43071042/126275216-2a422a64-02e0-4979-b1ba-a3efb6b3b918.png)
> https://hfish.io/#/

感谢回复，额，我想问一下，那个全球态势感知图功能在哪找到，我没找到

**Comment by WaterWei** [comment]
> > ![image](https://user-images.githubusercontent.com/43071042/126275216-2a422a64-02e0-4979-b1ba-a3efb6b3b918.png)
> > https://hfish.io/#/
> 
> 感谢回复，额，我想问一下，那个全球态势感知图功能在哪找到，我没找到

那个是0.6.x版本的功能，新版本重构后，这个功能还没有做。

**Comment by muyuanjin999** [comment]
> > > ![image](https://user-images.githubusercontent.com/43071042/126275216-2a422a64-02e0-4979-b1ba-a3efb6b3b918.png)
> > > https://hfish.io/#/
> > 
> > 
> > 感谢回复，额，我想问一下，那个全球态势感知图功能在哪找到，我没找到
> 
> 那个是0.6.x版本的功能，新版本重构后，这个功能还没有做。

嗯嗯，谢谢

**Comment by ClarkQAQ** [comment]
好吧....再见

**Comment by my417** [comment]
不必这么早说再见，我们下下个版本会有大屏，已经在开发了，春节之前能看到。
