### ISSUE TITLE
后台管理页面的一些显示 bug

### ISSUE THREAD

**Issue by xirikm** [hacklcx/HFish#16]
我设置了 SSH 蜜罐为高交互模式（配置文件中 status 设为 2）
然后发现后台的服务状态处显示 SSH 是关闭的，如下图：
![V9Wx.jpg](https://img.xirikm.net/images/V9Wx.jpg)
经测试，发现只有 status 设为 1 的时候后台服务状态处才不会显示关闭（有小红点）
虽然不是啥功能 bug ，但还是提一下吧，望尽快修复。

另外，后台显示攻击 ip 的扇形图在 ip 多了之后会越界导致显示不全，希望能够有一些优化（例如只将攻击次数多的 ip 地址列出之类的。
![VR4H.jpg](https://img.xirikm.net/images/VR4H.jpg)

**Comment by sanjinhub** [comment]
十分感谢！这个问题已经知道了，准备下个版本修复。欢迎进群
