### ISSUE TITLE
loop readonly分区占用100%误报 &磁盘CPU告警无法取消

### ISSUE THREAD

**Issue by burpheart** [hacklcx/HFish#161]
/dev/loop* 伪设备被识别成磁盘 频繁发出磁盘占用告警
告警策略未选择通知系统通知 但仍向HOOKAPI推送磁盘占用告警

**Comment by WaterWei** [comment]
问题收到，晚些尝试复测实现一下。

**Comment by my417** [comment]
新版后这个问题还存在么？我们一直没有发现这个问题。
