### ISSUE TITLE
部分页面出现乱码

### ISSUE THREAD

**Issue by zhanying233** [hacklcx/HFish#162]
运行环境：WIndows 2008 R2 数据中心版
![QQ截图20210901225206](https://user-images.githubusercontent.com/37135273/131694613-d5910dac-23ec-4f67-a0f9-c8bd892d9fe9.png)
![乱码1](https://user-images.githubusercontent.com/37135273/131694620-3b611df4-2aad-4e96-80b4-a5e684f548be.png)
![乱码2](https://user-images.githubusercontent.com/37135273/131694625-95aa61fc-a996-48f0-8ba1-66b680181d8d.png)
![乱码3](https://user-images.githubusercontent.com/37135273/131694627-dc30f74b-55b9-4136-9c14-155b2db08025.png)

**Comment by WaterWei** [comment]
乱码问题通常是数据库编码的问题，如果您用mysql数据库的话，不要用utf8，试试utf8mb4
