### ISSUE TITLE
mysql是安装时候内置的吗，还是自己下载安装后在部署hfish呢？

### ISSUE THREAD

**Issue by tangjie1** [hacklcx/HFish#165]
mysql是安装时候内置的吗，还是自己下载安装后在部署hfish呢？

**Comment by tangjie1** [comment]
我自己安装了mysql，但是一直连接不上去
![image](https://user-images.githubusercontent.com/40255379/143211056-93c12a05-38ec-48b7-bb8b-bebbc97ea821.png)

**Comment by tangjie1** [comment]
使用其他工具连接mysql正常，所以应该是系统配置上有什么问题嘛？

**Comment by my417** [comment]
没有默认自带mysql，需要用户自己安装，
无法连接的原因是2.7有个bug，mysql密码是不是用特殊字符了？改成字符和数字就应该可以了。

**Comment by Oldman19** [comment]
竟然不默认带mysql，可真low 啊

**Comment by my417** [comment]
> 

怎么样，解决了么？

**Comment by my417** [comment]
> 使用其他工具连接mysql正常，所以应该是系统配置上有什么问题嘛？

怎么样，解决了么？

**Comment by my417** [comment]
> 我自己安装了mysql，但是一直连接不上去 ![image](https://user-images.githubusercontent.com/40255379/143211056-93c12a05-38ec-48b7-bb8b-bebbc97ea821.png)

这个问题是因为mysql默认仅允许127登录，你用别的连接工具上去，修改一下root登录来源限制就行

**Comment by tangjie1** [comment]
解决了，好像是必须默认的账号密码才行

**Comment by my417** [comment]
虽然我也是懵逼状态，但是解决了就好
