### ISSUE TITLE
API: {"response_code":1004,"verbose_msg":"请求数据非法"}

### ISSUE THREAD

**Issue by userrrrrrrr** [hacklcx/HFish#170]
unable to use the build in API post examples in tools like postman.

HTTP 200 OK, message, but with the following body:
{"response_code":1004,"verbose_msg":"请求数据非法"}

Running 2.7.0 in docker-compose

**Comment by my417** [comment]
这是一个已知bug，下一个版本会修复

**Comment by JeffandJack** [comment]
> unable to use the build in API post examples in tools like postman.
> 
> HTTP 200 OK, message, but with the following body: {"response_code":1004,"verbose_msg":"请求数据非法"}
> 
> Running 2.7.0 in docker-compose
remove double quotes from the number which is the value of the parameter just like intranet and source.
