### ISSUE TITLE
linux/arm64/v8 errror

### ISSUE THREAD

**Issue by Ran-Xing** [hacklcx/HFish#172]
```bash
➜  ~ docker run -itd --name hfish \
-v /usr/share/hfish:/usr/share/hfish \
--network host \
--privileged=true \
threatbook/hfish-server:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2b1e98d09c5e2663cca00bbdb18ee138e11a68cc24cd120210288f0ae995aa0f
```

能够拉我参加hfish 的适配计划吗？我会跨架构编译

**Comment by my417** [comment]
HFish有一个arm版本，但在官网没上架，你可以扫二维码进群，我们给你一个安装包，你自己给docker做适配。

**Comment by XRSec** [comment]
@my417  qq群号方便发一下嘛？

**Comment by XRSec** [comment]
@my417 群已经满人了

**Comment by my417** [comment]
我们已经修复了你再试试？

**Comment by my417** [comment]
我们已经修复了，你扫官网的试试？
http://img.threatbook.cn/hfish/image-20211221132836482.png

**Comment by MrZhengI** [comment]
[root@localhost ~]# docker run -itd --name hfish \
> -v /usr/share/hfish:/usr/share/hfish \
> --network host \
> --privileged=true \
> threatbook/hfish-server:latest
Unable to find image 'threatbook/hfish-server:latest' locally
latest: Pulling from threatbook/hfish-server
a0d0a0d46f8b: Pull complete 
382cc710fed5: Pull complete 
1047d8f00aa6: Pull complete 
cc0b9984a850: Pull complete 
897dd64bd729: Pull complete 
34996daf010b: Pull complete 
3635fed1290d: Extracting [==================================================>]  121.1MB/121.1MB
Digest: sha256:be4af8b9ae9290b8e9c6f439c6ec8f9b78abb2f83d83948be55f5ea94dd38988
Status: Downloaded newer image for threatbook/hfish-server:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by MrZhengI** [comment]
如何解决。群已满

**Comment by LostDevops** [comment]
你好，图片已失效，可以咨询下docker怎么部署arm架构hfish吗，买找到dockerfile
