### ISSUE TITLE
Is the purpose to be more realistic?

### ISSUE THREAD

**Issue by ggWithZhou** [hacklcx/HFish#23]
如果要在外部进行连接时觉得更逼真的话，应该在最初进行连接的时候，加入一点点的随机延迟。比如：time.Sleep(time.Millisecond * time.Duration(rand.Intn(300)))
以上来自实际使用的一点体验。

If you want to make the connection more realistic, there should be a little delay, random delay. Now the result's returning too fast.
This is the experience from actual use.

**Comment by sanjinhub** [comment]
真的应该是在你本地测试的效果吧？如果放在网络上，存在网络延迟，我相信一定不会很快。
