### ISSUE TITLE
云端高交互蜜罐无法使用

### ISSUE THREAD

**Issue by snotrain** [hacklcx/HFish#232]
云端高交互蜜罐无法使用
网址无法ping通
![image](https://github.com/hacklcx/HFish/assets/172097755/67246b85-7981-423d-b4d4-bd6d58b2c668)

**Comment by leoljz** [comment]
![屏幕截图 2024-07-16 200434](https://github.com/user-attachments/assets/66f1699c-1795-4baa-9259-f27dbf2229aa)
