### ISSUE TITLE
后台记录命令错误

### ISSUE THREAD

**Issue by l0ca1** [hacklcx/HFish#25]
记录的命令在后台显示存在xss

**Comment by sanjinhub** [comment]
有截图嘛？

**Comment by l0ca1** [comment]
![image](https://user-images.githubusercontent.com/23295562/64315834-bb661280-cfe5-11e9-88ec-c5b6532a5664.png)

![image](https://user-images.githubusercontent.com/23295562/64315859-cf117900-cfe5-11e9-9c9e-3ecc84976326.png)


![image](https://user-images.githubusercontent.com/23295562/64315798-a2f5f800-cfe5-11e9-8596-b1a9f8b7de1e.png)

**Comment by sanjinhub** [comment]
OK，因为是内部平台，没有做那么多安全限制，前期主要做核心功能，后期这些东西都会加上。
