### ISSUE TITLE
docker仅映射config.ini后目录为空？

### ISSUE THREAD

**Issue by wolance** [hacklcx/HFish#27]
hi 很抱歉打扰你们。我在用docker构建后，并没有像   /hfish/:/opt/HFish/ 整个目录。。而是 仅仅映射  /hfish/config.ini:/opt/HFish/config.ini 但貌似这样，docker启动后则报  ./HFish not found，说明目录被清空了。希望可以得到答复。

**Comment by sanjinhub** [comment]
为什么要挂载目录，直接 -p 修改端口即可

**Comment by wolance** [comment]
o bro，感谢您能回复。  我希望可以  只挂在config.ini文件和hfish.db文件，修改config我是希望可以停掉不想用的蜜罐端口，虽然-p可以达到目的，但服务运行在docker中，是否会消耗资源。  hfish.db的映射，我希望在我进行部署时，就有已初始化的webhook可用，不需要对使用者可见，或配置

**Comment by sanjinhub** [comment]
docker 貌似不能挂载 文件吧，只能挂载目录，如果想挂载就需要整个文件夹，不如使用安装包二进制方式启动方便。

**Comment by wolance** [comment]
我有挂载过其他镜像，文件是可以挂载的吧。不过我打算再验证一下。当然，这不是你们的问题。
不过仍然建议，可以把输入输出与程序分离，通常用户都是会修改输入，查看输出的。仅仅建议。你们做的很棒，期待下个迭代。

**Comment by sanjinhub** [comment]
@wolance 感谢支持，可以进群，方便及时同步消息
