### ISSUE TITLE
运行一段时间后，panic 异常退出

### ISSUE THREAD

**Issue by deepdetail** [hacklcx/HFish#29]
版本：v0.3

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x9bc1d0]

goroutine 11364 [running]:
sync.(*RWMutex).RLock(...)
        /usr/local/go/src/sync/rwmutex.go:48
database/sql.(*Stmt).ExecContext(0x0, 0xddfbe0, 0xc000094020, 0xc00379bf90, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:2307 +0x50
database/sql.(*Stmt).Exec(...)
        /usr/local/go/src/database/sql/sql.go:2336
HFish/core/dbUtil.Update(0xcca995, 0x32, 0xc00379bf90, 0x2, 0x2, 0x0)
        /ext-go/1/src/HFish/core/dbUtil/dbUtil.go:87 +0xd9
HFish/core/report.ReportUpdateSSH(0xc0002da0d4, 0x4, 0xcaa51c, 0x2)
        /ext-go/1/src/HFish/core/report/report.go:227 +0x109
created by HFish/core/protocol/ssh.Start.func1
        /ext-go/1/src/HFish/core/protocol/ssh/ssh.go:59 +0x5b4

**Comment by sanjinhub** [comment]
请更新 0.3.1 ，另外请看官网文档！有暂时的奔溃解决方案！
