### ISSUE TITLE
3.1不能记录ssh mysql等行为

### ISSUE THREAD

**Issue by SamoulY** [hacklcx/HFish#31]
我升成3.1发现 本地测试记录不了mysql ssh telnet等行为，还没排查问题在哪了，测试环境docker debian

**Comment by sanjinhub** [comment]
是否可以连接？

**Comment by SamoulY** [comment]
ssh 高交互可以正常连接，可以返回信息，web 后台无法捕捉操作信息

On 日, 9月 15, 2019 at 8:01 下午, SanJin <notifications@github.com> wrote:

是否可以连接？

**Comment by sanjinhub** [comment]
@SamoulY 请更新版本到 0.3.2
