### ISSUE TITLE
启动直接崩溃

### ISSUE THREAD

**Issue by xueshaobo1** [hacklcx/HFish#38]
启动直接崩溃，运行环境2核2g centos 7 0.3.2版本二进制运行
2019/10/11 13:22:34 worker exits from a panic: runtime error: invalid memory address or nil pointer dereference
2019/10/11 13:22:34 worker exits from a panic: runtime error: invalid memory address or nil pointer dereference
2019/10/11 13:22:34 worker exits from panic: goroutine 68 [running]:
HFish/vendor/github.com/panjf2000/ants.(*Worker).run.func1.1(0xc0005fd650)
	/ext-go/1/src/HFish/vendor/github.com/panjf2000/ants/worker.go:59 +0x13e
panic(0xc571c0, 0x15d8330)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
HFish/core/protocol/mysql.Start.func1()
	/ext-go/1/src/HFish/core/protocol/mysql/mysql.go:66 +0x12e
HFish/vendor/github.com/panjf2000/ants.(*Worker).run.func1(0xc0005fd650)
	/ext-go/1/src/HFish/vendor/github.com/panjf2000/ants/worker.go:71 +0x9b
created by HFish/vendor/github.com/panjf2000/ants.(*Worker).run
	/ext-go/1/src/HFish/vendor/github.com/panjf2000/ants/worker.go:49 +0x4d

**Comment by sanjinhub** [comment]
Mysql 端口冲突？你改下配置文件 Mysql 的端口试试

**Comment by xueshaobo1** [comment]
感谢您，确实是这样



> Mysql范围冲突？你改下配置文件Mysql的端口试试
