### ISSUE TITLE
关于后台运行

### ISSUE THREAD

**Issue by timwhitez** [hacklcx/HFish#4]
该蜜罐我使用ssh启动，如何后台一直运行，退出ssh后还在线？

**Comment by sanjinhub** [comment]
@timwhitez 目前本身还不支持后台运行，推荐

1、./HFish run & 然后 输入 exit 退出即可
2、supervisord 启动
3、shell nohup 

具体使用哪种方式，自行百度对比下即可。

**Comment by timwhitez** [comment]
谢谢！

**Comment by geekyouth** [comment]
screen -S keep-hfish
