### ISSUE TITLE
发送邮件失败 5.0版本

### ISSUE THREAD

**Issue by xiaodaocool** [hacklcx/HFish#47]
![image](https://user-images.githubusercontent.com/18043903/70522977-05c6d480-1b7d-11ea-9f88-f81d9484e55b.png)

**Comment by sanjinhub** [comment]
看下日记，是否有报错

**Comment by xiaodaocool** [comment]
![image](https://user-images.githubusercontent.com/18043903/70584394-e91db180-1bfb-11ea-9e18-ab5a104001b6.png)
日志里面没看到具体原因

**Comment by sanjinhub** [comment]
输入邮件内容了吗？

**Comment by xiaodaocool** [comment]
标题和内容都是test

**Comment by sanjinhub** [comment]
@xiaodaocool 有时间我测试下
