### ISSUE TITLE
上钩列表没有记录来源ip

### ISSUE THREAD

**Issue by M4ple** [hacklcx/HFish#49]
telnet，memcache，redis蜜罐存在有上钩记录但来源ip为空的情况：
![image](https://user-images.githubusercontent.com/20105432/70900400-b2003380-2033-11ea-99b0-9838325ed6bc.png)
查看记录信息，发现有一些是http头的部分信息：
<img width="158" alt="image" src="https://user-images.githubusercontent.com/20105432/70900539-04415480-2034-11ea-9f65-3faa29d5d5df.png">
还有记录信息为空或其他杂乱信息的情况。
不知道这是什么情况，如果需要其他信息请回复。

**Comment by sanjinhub** [comment]
这种的 是 客户端 bug, 正在解决中。。。

**Comment by leezp** [comment]
我的来源ip显示的本机ip
