### ISSUE TITLE
web蜜罐能自定义钓鱼页面吗

### ISSUE THREAD

**Issue by 98Kstar** [hacklcx/HFish#52]
web蜜罐可以自定义页面吗？伪装成其他登陆页面

**Comment by sanjinhub** [comment]
可以的

**Comment by 98Kstar** [comment]
您好，伪装了wordpress下的模版，并生成了自己想要的钓鱼界面，但是新生成的钓鱼页面无法在9001页面记录下密码，请问如何修改

**Comment by 98Kstar** [comment]
师傅你好，我在自定义了自己的钓鱼界面后，并按照x.js中的要求配置了html页面中的username，与password的变量名，但是后台记录了IP地址但是账号密码却总是显示undefined，不知道何原因
