### ISSUE TITLE
report  xss

### ISSUE THREAD

**Issue by 963230432** [hacklcx/HFish#53]
web蜜罐的static/x.js上报的数据包中name参数存在xss问题。

**Comment by 963230432** [comment]
另外，大屏展现做的真的超级棒！

**Comment by N407PengYuYan** [comment]
> 
> 
> web蜜罐的static/x.js上报的数据包中name参数存在xss问题。

厉害👍

**Comment by sanjinhub** [comment]
@963230432 收到，我试试。大屏还不是很完善，感谢支持。
