### ISSUE TITLE
worker exits from a panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by geekyouth** [hacklcx/HFish#56]
![image](https://user-images.githubusercontent.com/12899262/72620471-526eae00-397a-11ea-8dde-168d60a60e43.png)

centos6  部署，运行报错
worker exits from a panic: runtime error: invalid memory address or nil pointer dereference

**Comment by sanjinhub** [comment]
流量很大吧？

**Comment by xisafe** [comment]
invalid memory address  同样的错误

**Comment by xisafe** [comment]
阿里云

**Comment by geekyouth** [comment]
> 流量很大吧？

还没启动完成呢，和流量没关系吧

**Comment by 0FuzzingQ** [comment]
同样的错误 请问lz解决了吗？
