### ISSUE TITLE
关于cahe写入报错问题

### ISSUE THREAD

**Issue by lzy1102** [hacklcx/HFish#58]
github.com/panjf2000/ants v1.2.0 使用 go mod download 下载报错，升级1.3.0后成功；但是运行代码报错，详情如下

[GIN-debug] POST   /api/v1/post/plug_report  --> HFish/view/api.ReportPlugWeb (3 handlers)
panic: interface conversion: interface {} is nil, not int64

goroutine 1 [running]:
HFish/utils/setting.initCahe()
        E:/GoProject/src/HFish-0.5/utils/setting/setting.go:155 +0x846
HFish/utils/setting.Run()
        E:/GoProject/src/HFish-0.5/utils/setting/setting.go:369 +0xec0
main.main()
        E:/GoProject/src/HFish-0.5/main.go:10 +0x2d
exit status 2

**Comment by lzy1102** [comment]
解决了，替换源码编译后产生的hfish.db文件以后可以了，但是具体原因还没找到

**Comment by sanjinhub** [comment]
旧数据库文件 少字段

**Comment by shiyishiaa** [comment]
> 大佬 问一下这个问题是怎么解决的呢？我自己go build出来的 启动也有这个问题 不过hfish.db 这个文件是空的

下载同版本的release包，替换hfish.db文件
