### ISSUE TITLE
请问按照集群部署步骤，客户端无法启动的原因是什么？

### ISSUE THREAD

**Issue by zcdy** [hacklcx/HFish#59]
两台VPS，服务端按步骤配置完毕，也启动成功了。
但客户端vps，按官方文档配置后，一直启动不成功，报错信息如下，请问是什么原因？
![image](https://user-images.githubusercontent.com/4179930/75084404-da883a80-555a-11ea-975e-884870671e32.png)
![image](https://user-images.githubusercontent.com/4179930/75084409-e2e07580-555a-11ea-85fb-67ef56b3670f.png)

**Comment by sanjinhub** [comment]
第一个问题 数据库连接失败
第二个问题 WEB目录路径好像不对

**Comment by hikid** [comment]
服务器和客户端都已经成功启动，上钩列表中也能检测到连接信息，但是分布式集群中没有客户端的存活情况，会是什么原因呢？防火墙都已经全关了。
