### ISSUE TITLE
Docker with Web Api ERROR!

### ISSUE THREAD

**Issue by Hatcat123** [hacklcx/HFish#6]
hi! hacklcx!!! When I simulated the process of using docker to build HFish quickly in a public network server, I found unexpected problems with JS in the WEB project.
```
docker exec -it hfish /bin/sh
cat config.ini
```
```
[api]
status = 1                                   # 是否启动 API 1 启动 0 关闭
web_url = /api/v1/post/report                # 管理后台启动地址
deep_url = /api/v1/post/deep_report          # 管理后台启动地址

```
Than error show that:
```
cat x.js 
```

```
function report() {
    var login_field = $("#user_login").val();
    var password = $("#user_pass").val();

    $.ajax({
        type: "POST",
        url: "http://localhost:9001/api/v1/post/dart_report",
```
In branch **dev**  `deep_report`= `dart_report`, so an Api about dart_report not found. 

But the problem has been fixed in branch **master**

I recommend using `master` to build docker image

**Comment by sanjinhub** [comment]
Docker Updated.
