### ISSUE TITLE
the client name can XSS

### ISSUE THREAD

**Issue by N407PengYuYan** [hacklcx/HFish#61]
![20200226213922](https://user-images.githubusercontent.com/45984360/75353262-15d19300-58e6-11ea-9b2f-94205a0b474e.jpg)
Modify the client config.ini file in a distributed cluster where the client name constructs an XSS statement to attack the server
> [rpc]
status = 2                                      # 模式 0关闭 1服务端 2客户端
addr = x.x.x.x:7879                             # RPC 服务端地址 or 客户端地址
name = **_< img src=x onerror=alert(1)>_**                                  # 状态1 服务端 名称 状态2 客户端 名称

**Comment by sanjinhub** [comment]
收到，新版本会解决这个问题
