### ISSUE TITLE
蜜罐系统很直观简洁，提0.5.1版本的两个问题

### ISSUE THREAD

**Issue by wangyouwei2016** [hacklcx/HFish#65]
1.邮件发送不可用
提示：[GIN] 2020/03/10 - 16:18:30 | 200 |     425.828µs |    10.32.166.24 | GET      /get/setting/info?id=1
[HFish] 127.0.0.1 - [2020-03-10 16:18:42] 发送邮件通知失败  [EOF]
2.客户端连接正常，功能也正常，上钩列表有内容，但是分布式列表中不显示任何信息。

**Comment by sanjinhub** [comment]
1、邮件请提供详细配置截图
2、0.5.1 会出现这个问题，等新版本
