### ISSUE TITLE
webhook调用成功 并没有信息通知到微信

### ISSUE THREAD

**Issue by xisafe** [hacklcx/HFish#66]
tail: hfish.log: file truncated
[HFish] 127.0.0.1 - [2020-03-11 16:21:28] WebHook 调用成功  []
[HFish] 127.0.0.1 - [2020-03-11 16:21:30] WebHook 调用成功  []
[HFish] 127.0.0.1 - [2020-03-11 16:21:31] WebHook 调用成功  []
[HFish] 127.0.0.1 - [2020-03-11 16:21:32] WebHook 调用成功  []
[HFish] 127.0.0.1 - [2020-03-11 16:21:50] WebHook 调用成功  []

**Comment by sanjinhub** [comment]
请查看你写的API 是否有请求记录
