### ISSUE TITLE
建议将管理页面所有绝对路径修改为相对路径

### ISSUE THREAD

**Issue by issueser** [hacklcx/HFish#70]
在反向代理使用二级目录时，绝对路径会导致一些问题，建议修改成相对路径。
如未登录情况下访问http://example.com/hfish/ 会跳转http://example.com/login 而不是http://example.com/hfish/login
页面资源也是一样的。
谢谢。

**Comment by sanjinhub** [comment]
收到 会在未来某个版本解决
