### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by issueser** [hacklcx/HFish#72]
环境：releases0.5.1 + mysql模式
建议：
1.地理位置信息可以开关设置启用禁用；
2.同IP地理位置信息不重复记录，缩小数据库大小，最好可以直接单独开表记录位置，靠ID定义；
3.SSH高交互模式参数配置可以使用变量；
4.hfish_passwd中重复的账号密码只记录一次，缩小数据库大小；
5.hfish_info中project_name最好单独开表定义名字，靠ID定义，缩小数据库大小；
6.api可以增加些查询参数，如黑名单api增加获取的时间范围，密码api增加topN查询
本人小白，目前使用起来挺舒服，已Star，希望大佬可以一直维护下去。

**Comment by sanjinhub** [comment]
收到，感谢你的建议！目前还在测试版本，还不成熟，后续会往这方面开发。
