### ISSUE TITLE
SSH服务获取命令行输入时键入EOF造成死循环

### ISSUE THREAD

**Issue by AnneviLL** [hacklcx/HFish#80]
### 问题简述
蜜罐的ssh服务在接受用户终端输入时未进行错误处理,导致当攻击者键入`Ctrl+D (EOF)`时
```golang
line, _ = term.ReadLine()
```
抛出错误，但循环并未结束，因此造成死循环，无限执行
```golang
if is.Rpc() {
	id = client.ReportResult("SSH", "", arr[0], info, "0")
} else {
	id = strconv.FormatInt(report.ReportSSH(arr[0], "本机", info), 10)
}
```
造成DDOS，使蜜罐服务器拒绝服务,并在数据库中产生大量垃圾数据。
![image](https://user-images.githubusercontent.com/42777299/79971894-a2a06380-84c7-11ea-870c-cfa39a55a2d3.png)
![image](https://user-images.githubusercontent.com/42777299/79971943-b6e46080-84c7-11ea-90c5-ebdd492f9a80.png)

### 测试环境
macOS Catalina 10.15.3
go1.13.4 darwin/amd64

### 修复建议
对`term.ReadLine()`做错误处理，如下：
```golang
if err != nil {
	break
}
```

**Comment by sanjinhub** [comment]
很强，感谢反馈。
