### ISSUE TITLE
从HFish 0.5升级上来之后启动失败，缺少配置密码脱敏符号设置

### ISSUE THREAD

**Issue by cnzzr** [hacklcx/HFish#82]
HFish 0.6 版本新增配置“密码脱敏符号设置”
此项为空时造成启动失败，请进行修复。

INSERT INTO `hfish_setting` VALUES ('1', 'passwdTM', '', '2019-09-02 20:15:00', '0', '密码脱敏符号设置', '密码脱敏符号设置')

**Comment by sanjinhub** [comment]
新版本0.6 Sql 已经包含
