### ISSUE TITLE
用awvs扫描器扫web蜜罐站点发现程序直接报错退出

### ISSUE THREAD

**Issue by jiangsi520** [hacklcx/HFish#83]
用awvs扫描器扫web蜜罐发现程序直接报错退出请问这个是什么原因是不是哪里需要配置？
![image](https://user-images.githubusercontent.com/30169495/80692806-b752ac00-8b04-11ea-9479-55b9fcc0b45a.png)

**Comment by sanjinhub** [comment]
不能为空，新版本会解决
