### ISSUE TITLE
建议 上钩列表这里能不能增加个全选的功能？

### ISSUE THREAD

**Issue by jiangsi520** [hacklcx/HFish#84]
日志量比较大,建议上钩列表这里能不能增加个全部删除的功能？另外下面这个报错是什么意思数据库文件没权限？还是文件过大写不进去了？
![image](https://user-images.githubusercontent.com/30169495/81467815-cffe4880-920d-11ea-8f15-ce98d53d489d.png)
![image](https://user-images.githubusercontent.com/30169495/81468380-caa2fd00-9211-11ea-9085-369911fd9762.png)

**Comment by sanjinhub** [comment]
新版本已经有清空全部上钩数据功能，这个数据库插入 BUG 我来查查
