### ISSUE TITLE
希望增加非安全连接的邮件发送

### ISSUE THREAD

**Issue by heidaren** [hacklcx/HFish#93]
公司邮件系统不支持安全连接方式发送邮件，希望能增加普通邮件的发送配置

**Comment by sanjinhub** [comment]
@heidaren 最新版本已经修复，目前是可以用的。

**Comment by heidaren** [comment]
我重新下载了0.6.2然后使用0.6.3覆盖了HFish文件和static下的data.js文件，再使用时还是报没加密的错误，页面显示版本还是0.6.2，是我哪里操作有问题么

**Comment by sanjinhub** [comment]
@heidaren 0.6.3 没有更新HTML，所以页面上版本号没有变，这是正常的

**Comment by heidaren** [comment]
@sanjinhub 我意思是我都更新成最新版了但是发邮件还是提示没有加密无法发声，还需要修改什么东西么？
