### ISSUE TITLE
打开配置文件失败

### ISSUE THREAD

**Issue by M0dred** [hacklcx/HFish#97]
打开配置文件失败  [open ./config.ini: no such file or directory]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xa2046e]

已下载 HFish-0.6.3-linux-amd64.tar.gz
cd HFish-0.6.3-linux-amd64
./HFish run

**Comment by sanjinhub** [comment]
看下周说明
