### ISSUE TITLE
集群部署，没有IP信息

### ISSUE THREAD

**Issue by 0kk4cce1er** [hacklcx/HFish#99]
集群构建，用的mysql
1.server端用的0.6.3
2.client端用的0.6.2

**Comment by 0kk4cce1er** [comment]
![Snipaste_2020-05-24_15-20-19](https://user-images.githubusercontent.com/38617792/82748160-6025bb80-9dd2-11ea-8bc1-7531a2550eb7.png)
![Snipaste_2020-05-24_15-20-36](https://user-images.githubusercontent.com/38617792/82748163-6451d900-9dd2-11ea-922e-accba297f71f.png)

**Comment by sanjinhub** [comment]
怀疑 客户端挂掉，你查看客户端是否正常，重启试试

**Comment by 0kk4cce1er** [comment]
@sanjinhub 客户端挂掉就不会有消息传到server端吧，查看客户端没有问题，只是数据没有IP字段。

**Comment by 0kk4cce1er** [comment]
修好了，用master分支重新构建使用client
